apiVersion: v1
kind: Pod
metadata:
  name: kubeturbo
  labels:
    name: kubeturbo
spec:
  hostNetwork: true
  containers:
  - name: kubeturbo
    image: dongyiyang/kubeturbo:dev
    command:
      - /bin/kubeturbo
    args:
      - --v=3
      - --master=http://127.0.0.1:8080
      - --etcd-servers=http://127.0.0.1:4001
      - --config-path=/etc/kubeturbo/config
    volumeMounts:
    - name: vmt-config
      mountPath: /etc/kubeturbo
      readOnly: true
  volumes:
  - name: vmt-config
    hostPath:
      path: /home/dongyiyang/Sandbox/Go/src/k8s.io/kubernetes/vmt_testing/kubeturbo/Configuration
  restartPolicy: Always