apiVersion: v1
kind: Pod
metadata:
  name: cadvisor
  labels:
    name: cadvisor
spec:
  containers:
  - name: cadvisor_2
    image: google/cadvisor:latest
    command:
      - /bin/kubeturbo
    args:
      - --v=3
      - --master=10.10.150.150:8080
      - --etcd-servers=http://10.10.150.150:2379
      - --config-path=/etc/kubeturbo/config
    volumeMounts:
    - name: vmt-config
      mountPath: /etc/kubeturbo
      readOnly: true
  volumes:
  - name: vmt-config
    hostPath:
      path: /etc/kubeturbo
  restartPolicy: Always