apiVersion: v1
kind: Secret
metadata:
  name: vmturbo-configuration
data:
  config.json: ewoJCSJzZXJ2ZXJhZGRyZXNzIjoJIjEwLjEwLjE5Mi42OTo4MDgwIiwKCQkidGFyZ2V0dHlwZSI6Ikt1YmVybmV0ZXMiLAoJCSJuYW1lb3JhZGRyZXNzIjogICJrOHNfdm10IiwKCQkidXNlcm5hbWUiOiJrdWJlcm5ldGVzX3VzZXIiLAoJCSJ0YXJnZXRpZGVudGlmaWVyIjogIm15X2s4cyIsCgkJInBhc3N3b3JkIjoiZmFrZV9wYXNzd29yZCIsCgkJImxvY2FsYWRkcmVzcyI6Imh0dHA6Ly8xMjcuMC4wLjEvIiwKCQkid2Vic29ja2V0dXNlcm5hbWUiOiAidm10UmVtb3RlTWVkaWF0aW9uIiwKCQkid2Vic29ja2V0cGFzc3dvcmQiOiAidm10UmVtb3RlTWVkaWF0aW9uIiwKCQkidm10dXNlcm5hbWUiOiAiYWRtaW5pc3RyYXRvciIsCgkJInZtdHBhc3N3b3JkIjogImEiCn0K